export const SET_MOVIES = "SET_MOVIES";
export const SET_SERIES = "SET_SERIES";
export const SET_CURRENT_SEARCH = "SET_CURRENT_SEARCH";

export const SET_MOVIE_CURRENT_PAGE = "SET_MOVIE_CURRENT_PAGE";
export const SET_MOVIE_PREV_PAGE = "SET_MOVIE_PREV_PAGE";
export const SET_MOVIE_NEXT_PAGE = "SET_MOVIE_NEXT_PAGE";

export const SET_SERIE_CURRENT_PAGE = "SET_SERIE_CURRENT_PAGE";
export const SET_SERIE_PREV_PAGE = "SET_SERIE_PREV_PAGE";
export const SET_SERIE_NEXT_PAGE = "SET_SERIE_NEXT_PAGE";
